export default function History({ fill }: React.SVGProps<SVGSVGElement>) {
  return (
    <svg width="100%" height="100%" viewBox="0 0 101 101" fill="none">
      <rect
        x="1.5"
        y="1.5"
        width="26"
        height="26"
        rx="3.5"
        fill={fill}
        stroke={fill}
        strokeWidth="3"
      />
      <rect
        x="37.5"
        y="1.5"
        width="26"
        height="26"
        rx="3.5"
        fill={fill}
        stroke={fill}
        strokeWidth="3"
      />
      <rect
        x="73.5"
        y="1.5"
        width="26"
        height="26"
        rx="3.5"
        fill={fill}
        stroke={fill}
        strokeWidth="3"
      />
      <rect
        x="73.5"
        y="37.5"
        width="26"
        height="26"
        rx="3.5"
        stroke={fill}
        strokeWidth="3"
      />
      <rect
        x="1.5"
        y="37.5"
        width="26"
        height="26"
        rx="3.5"
        fill={fill}
        stroke={fill}
        strokeWidth="3"
      />
      <rect
        x="37.5"
        y="37.5"
        width="26"
        height="26"
        rx="3.5"
        fill={fill}
        stroke={fill}
        strokeWidth="3"
      />
      <rect
        x="73.5"
        y="73.5"
        width="26"
        height="26"
        rx="3.5"
        stroke={fill}
        strokeWidth="3"
      />
      <rect
        x="1.5"
        y="73.5"
        width="26"
        height="26"
        rx="3.5"
        stroke={fill}
        strokeWidth="3"
      />
      <rect
        x="37.5"
        y="73.5"
        width="26"
        height="26"
        rx="3.5"
        stroke={fill}
        strokeWidth="3"
      />
    </svg>
  );
}
